version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "4321:4321"
      - "8000:8000"
    environment:
      - PORT=8000
    command: "npm start"  
