version: "3.8"
services:
  app:
    build:
      context: ..
      dockerfile: .github/Dockerfile
    ports:
      - "4321:4321"
      - "8000:8000"
      - "8050:8050"
      - "8051:8051"
      - "8052:8052"
    environment:
      - PORT=8000
      - NODE_ENV=development  # Set the environment to development
    volumes:
      - ./src:/app/src  # Bind mount for the source code
      - ./bricks:/app/bricks  # Bind mount for bricks if needed
      - ./README.md:/app/README.md  # Bind mount for README if needed