services:
  app:
    build:
      context: ..
      dockerfile: .github/Dockerfile
    ports:
      - "4321:4321"
      - "8000:8000"
    volumes:
      - ../bricks:/app/bricks
    environment:
      - PORT=8000